# Generated by Django 4.2 on 2023-04-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='warzone_match_string',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
