# Generated by Django 4.2 on 2023-05-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameInfo', '0004_rename_game_id_stats_game_remove_stats_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameInfo.player'),
        ),
        migrations.AddField(
            model_name='stats',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameInfo.team'),
        ),
    ]
